#version: "3"

networks:
  gitea:
    external: false

services:
  gitea-server:
    image: docker.gitea.com/gitea:1
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=gitea-db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - GITEA__security__INSTALL_LOCK=true
      - GITEA__server__DOMAIN=192.168.1.11
      - GITEA__server__ROOT_URL=http://192.168.1.11:3033/
    restart: always
    networks:
      - gitea
    volumes:
      - /srv/confs/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3033:3000" #UI
      - "2234:22"
    depends_on:
      gitea-db:
        condition: service_healthy
 
  gitea-db:
    image: mysql:9.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - /srv/databases/gitea/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  user-creator-fastapi:
    build:
      context: ./user-creator-fastapi
    container_name: user-creator-fastapi
    restart: always
    networks:
      - gitea
    env_file:
      - ./user-creator-fastapi/.env
    environment:
      - PORT=8055
      # Ensure build root is shared between host and container
      - BUILD_ROOT=/srv/builds
    volumes:
      - /srv/builds:/srv/builds
      # Optionally mount source for live-editing instead of baked image
      # - ./user-creator-fastapi:/app:ro
    ports:
      - "8055:8055"
    depends_on:
      - gitea-server
