version: '3'

services:
  mongo:
    restart: always
    container_name: quant-ux-mongo
    image: mongo
    volumes:
      - ./data:/data/db

  qux-fe:
    restart: always
    container_name: quant-ux-frontend
    image: klausenschaefersinho/quant-ux
    environment:
      - QUX_PROXY_URL=http://quant-ux-backend:8080
      - QUX_AUTH=qux
      - QUX_WS_URL=ws://127.0.0.1:8086
    links:
      - mongo
      - qux-be
    ports:
      - 8085:8082
    depends_on:
      - qux-be

  qux-be:
    restart: always
    container_name: quant-ux-backend
    image: klausenschaefersinho/quant-ux-backend
    volumes:
      - ./quant-ux-data:/app-data
    environment:
      - QUX_HTTP_HOST=http://quant-ux-frontend:8082
      - QUX_HTTP_PORT=8080
      - QUX_MONGO_DB_NAME=quantux
      - QUX_MONGO_TABLE_PREFIX=quantux
      - QUX_MONGO_CONNECTION_STRING=mongodb://quant-ux-mongo:27017
      - QUX_MAIL_USER=mail_admin@example.com
      - QUX_MAIL_PASSWORD=sTr0ngPa55w0Rd
      - QUX_MAIL_HOST=mail.example.com
      - QUX_JWT_PASSWORD=some-long-jwt-secret
      - QUX_IMAGE_FOLDER_USER=/app-data/qux-images
      - QUX_IMAGE_FOLDER_APPS=/app-data/qux-image-apps
      - TZ=America/Chicago
      - QUX_AUTH_SERVICE=qux
      - QUX_USER_ALLOW_SIGNUP=true
      - QUX_USER_ALLOWED_DOMAINS=*
    depends_on:
      - mongo

  qux-ws:
    restart: always
    container_name: quant-ux-websocket-server
    image: klausenschaefersinho/quant-ux-websocket
    environment:
      - QUX_SERVER=http://quant-ux-backend:8080/
      - QUX_SERVER_PORT=8086
    ports:
      - 8086:8086
    links:
      - qux-be
    depends_on:
      - qux-be