#version: '3.8'

services:
  chartdb:
    image: ghcr.io/chartdb/chartdb:latest
    container_name: chartdb
    restart: unless-stopped
    ports:
      - "8060:80"
    environment:
      - OPENAI_API_KEY=<YOUR_OPEN_AI_KEY>