version: '3.8'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase-h2
    environment:
      - TZ=Europe/Madrid
      - MB_DB_TYPE=h2
      - MB_DB_FILE=/metabase-data/metabase.db
    ports:
      - "3000:3000"
    volumes:
      - metabase_data:/metabase-data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  metabase_data:
