version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: metabase-postgres
    environment:
      - POSTGRES_USER=metabase
      - POSTGRES_PASSWORD=metabase
      - POSTGRES_DB=metabase
      - TZ=Europe/Madrid
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - metanet
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metabase"]
      interval: 5s
      timeout: 5s
      retries: 5

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=metabase
      - MB_DB_PASS=metabase
      - MB_DB_HOST=postgres
      - TZ=Europe/Madrid
    ports:
      - "3000:3000"
    volumes:
      - metabase_data:/metabase-data
    networks:
      - metanet
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  metabase_data:

networks:
  metanet:
    driver: bridge
