#version: '3'
services:
  pigallery2:
    image: bpatrik/pigallery2:latest
    container_name: pigallery2
    environment:
      - NODE_ENV=production
    volumes:
      - "/home/your_rpi_user/Docker/pigallery/config:/app/data/config" # CHANGE ME
      - "db-data:/app/data/db"
      - "/home/your_rpi_user/Docker/nextcloud2/html/data/rejsikej/files/Photos:/app/data/images:ro" # CHANGE ME, ':ro' mean read-only
      - "/home/your_rpi_user/Docker/pigallery/tmp:/app/data/tmp" # CHANGE ME
    ports:
      - 81:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pigallery.rule=Host(`pigallery.jalcocertech.com`)"
      - "traefik.http.routers.pigallery.entrypoints=https"
      - "traefik.http.routers.pigallery.tls=true"
      - "traefik.http.routers.pigallery.tls.certresolver=cloudflare"
      - "traefik.http.services.pigallery.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.pigallery2.middlewares=default-security-headers@file"
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true    
volumes:
  db-data: