services:
  linkchecker:
    image: ghcr.io/linkchecker/linkchecker:10.6.0
    container_name: linkchecker
    user: "${UID:-1000}:${GID:-1000}"
    working_dir: /work
    volumes:
      - ./:/work
    stdin_open: true
    tty: true
    restart: "no"
