#version: "3"
services:
  pialert:
    container_name: pialert
    image: "jokobsk/pi.alert:latest"      
    network_mode: "host"        
    restart: always
    volumes:
      - ~/Docker/pialert/config:/home/pi/pialert/config
      - ~/Docker/pialert/db/pialert.db:/home/pi/pialert/db/pialert.db
      - ~/Docker/pialert/log/:/home/pi/pialert/log
    environment:
      - TZ=Europe/Berlin
      - PORT=20211
      - HOST_USER_ID=1000
      - HOST_USER_GID=1000