version: '3.8'

services:
  filebrowser:
    image: filebrowser/filebrowser:v2-s6
    container_name: filebrowser
    ports:
      - "8082:80"
    volumes:
      - ./config:/config
      - /home/jalcocert/EntreAgujayPunto:/srv  # Adjust this path as needed
    restart: unless-stopped
    networks:
      - cloudflared_tunnel

networks:
  cloudflared_tunnel:
    external: true  # This network should be created separately
