version: "2.1"

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9696:9696"
    restart: unless-stopped
    networks:
      - prowlarr-net

networks:
  prowlarr-net:
    driver: bridge
