services:
  firefox:
    image: ghcr.io/linuxserver/firefox
    container_name: firefox
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /home/pi/Docker/Firefox/config:/config
    ports:
      - 3000:3000
    shm_size: "1gb"
    restart: unless-stopped


version: "3.4"
services:
  neko:
    image: "m1k1o/neko:firefox" #there are more! brave, chromium,...
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "8888:8080"
      - "52000-52100:52000-52100/udp"
    environment:
      NEKO_SCREEN: 1920x1080@30
      NEKO_PASSWORD: neko #you will need this
      NEKO_PASSWORD_ADMIN: admin #and this
      NEKO_EPR: 52000-52100
      NEKO_ICELITE: 1
