services:
  umami: #https://github.com/umami-software/umami/releases
    image: ghcr.io/umami-software/umami:postgresql-latest ## ##admin // umami
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami
      DATABASE_TYPE: postgresql
      HASH_SALT: "your-very-strong-and-long-random-string" # Important!
      #openssl rand -base64 32
    depends_on:
      - db
    restart: always
    networks:
      - umami_network # Use a dedicated network
      - cloudflare_tunnel
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256" #Stronger authentication
    volumes:
      - ./sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro #Relative path
      - umami-db-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - umami_network #Use a dedicated network
volumes:
  umami-db-data:
networks:
  umami_network:
    driver: bridge #Explicitly define the network driver.
  # nginx_default:
  #   external: true     
  # cloudflare_tunnel:
  #   external: true