services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    ports:
      - 8031:80
    volumes:
      - ./config:/config
      - ./data:/srv #should match the photo tools
    restart: unless-stopped    
   # networks:
   #   - nginx_default #this will allow communication between this service and the existing nginx service  

###PHOTOVIEW
  #db:
   # image: linuxserver/mariadb
   # restart: always
   # environment:
      #- MYSQL_DATABASE=photoview
     # - MYSQL_USER=photoview
    #  - MYSQL_PASSWORD=photosecret
   #   - MYSQL_RANDOM_ROOT_PASSWORD=1
  #  volumes:
 #     - db_data:/var/lib/mysql
#      - /root/Docker/FileBrowser/data:/photos:ro #should match to FILEBROWSER
      #- /home/your/path/with/files/photos:/photos:ro #it respects your file system photo organization & remember to mention /photos/whatever_path in the initial setup 

volumes:
  db_data:
  api_cache:

networks:
  nginx_default:
    external: true
