services:
  termix:
    image: ghcr.io/lukegus/termix:latest
    container_name: termix
    restart: unless-stopped
    ports:
      - "8090:8080"
    volumes:
      - termix-data:/app/data
    environment:
      # Generate random salt here https://www.lastpass.com/features/password-generator (max 32 characters, include all characters for settings)
      SALT: "something_generated"
      PORT: "8080"
    networks:
      - traefik_traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.termix.entrypoints=http"
      - "traefik.http.routers.termix.rule=Host(`termix.x300.jalcocertech.com`)" #Tweak this with your subdomain
      - "traefik.http.middlewares.termix-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.termix.middlewares=termix-https-redirect"
      - "traefik.http.routers.termix-secure.entrypoints=https"
      - "traefik.http.routers.termix-secure.rule=Host(`termix.x300.jalcocertech.com`)" #Tweak this with your subdomain
      - "traefik.http.routers.termix-secure.tls=true"
      - "traefik.http.routers.termix-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.termix-secure.service=termix" #change this to your service name
      - "traefik.http.services.termix.loadbalancer.server.port=8080"      #it has to be the container port!!!
networks:
  traefik_traefik-proxy:
    external: true
volumes:
  termix-data:
    driver: local