FROM nginx:1.29-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY site/404.html /usr/share/nginx/html/404.html
COPY site/alphabets.js /usr/share/nginx/html/alphabets.js
COPY site/compress.js /usr/share/nginx/html/compress.js
COPY site/main.js /usr/share/nginx/html/main.js
COPY site/lean-qr /usr/share/nginx/html/lean-qr
