services:
    feishin:
        container_name: feishin
        image: 'ghcr.io/jeffvli/feishin:latest'
        environment:
            - SERVER_NAME=jellyfin
            - SERVER_LOCK=true
            - SERVER_TYPE=jellyfin
            - SERVER_URL=http://address:port
            - PUID=1000
            - PGID=1000
            - UMASK=002
            - TZ=Europe/Warsaw
        ports:
            - 9180:9180
        restart: unless-stopped
