
#sudo docker compose -f NC_Traefik.yml up -d
#nslookup nextcloud.jalcocertech.com

#version: '3.8'

volumes:
  nextcloud-db:

services:
  nextcloud-db:
    image: linuxserver/mariadb
    restart: always
    container_name: ncdb
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_INITDB_SKIP_TZINFO=1
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_PASSWORD=ncpass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - nc_network      

  nextcloud:
    image: nextcloud
    container_name: nc
    restart: always
    depends_on:
      - nextcloud-db
    ports:
      - 8035:80      
    volumes:
      - /home/jalcocert/Docker/nextcloud/html:/var/www/html
    environment:
      - MYSQL_PASSWORD=ncpass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - NEXTCLOUD_TRUSTED_DOMAINS=https://nextcloud.jalcocertech.com http://192.168.1.11:8035 #change this
    networks:
      - nc_network

networks:
  nc_network:
    driver: bridge