services:
  noet:
    image: ghcr.io/rishikanthc/noet:latest
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./data:/data
    environment:
      - NOET_DB_PATH=/data/noet.db
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/api/settings"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

# services:
#   db:
#     image: postgres:15-alpine
#     environment:
#       POSTGRES_USER: noet
#       POSTGRES_PASSWORD: noet_password
#       POSTGRES_DB: noet
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     restart: unless-stopped

#   backend:
#     image: rishikanthc/noet-backend:latest
#     depends_on:
#       - db
#     environment:
#       - DATABASE_URL=postgresql://noet:noet_password@db:5432/noet
#       - JWT_SECRET=your-jwt-secret-here
#       - PORT=3000
#     ports:
#       - "3000:3000"
#     restart: unless-stopped

#   frontend:
#     image: rishikanthc/noet-frontend:latest
#     depends_on:
#       - backend
#     environment:
#       - VITE_API_URL=http://localhost:3000
#     ports:
#       - "8080:80"
#     restart: unless-stopped

# volumes:
#   postgres_data:
