# Based on https://github.com/antiwork/gumroad/blob/main/docker/docker-compose-local.yml
# This stack provides the infrastructure services used by Gumroad for local/dev:
# - MySQL, Redis, MongoDB, Elasticsearch, and an optional Nginx reverse proxy
# It does NOT run the Gumroad Rails app container itself.

services:
  db:
    image: mysql:8.0.32
    container_name: gumroad-mysql
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
    command:
      - "mysqld"
      - "--default-authentication-plugin=mysql_native_password"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--character-set-server=utf8mb4"

  redis:
    image: redis:7.0.7
    container_name: gumroad-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongo:
    image: mongo:3.6.16
    container_name: gumroad-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: ["mongod", "--smallfiles"]

  elasticsearch:
    image: elasticsearch:7.9.3
    container_name: gumroad-elasticsearch
    restart: unless-stopped
    ports:
      - "9200:9200"
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
    volumes:
      - elasticsearch7data:/data

  # Optional: local reverse proxy to route dev domains to your host app
  nginx:
    image: nginx:1.23.3
    container_name: gumroad-nginx
    restart: unless-stopped
    volumes:
      - ./local-nginx/gumroad_dev.conf:/etc/nginx/conf.d/default.conf:Z
      - ./local-nginx/certs:/etc/ssl/certs/:Z
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      com.antiwork.helper.proxy: "true"

volumes:
  elasticsearch7data:
  mysql_data:
  redis_data:
  mongo_data:
