services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    ports:
      - "8096:8096"
    volumes:
      - "~/Docker/Jellyfin:/config"
      #- "/media/pi/Nowy:/data/tvshows"
      - "/home/jalcocert/Desktop/CAM4:/data/tvshows"
      - "/home/jalcocert/Desktop/CAM4:/data/movies"
    restart: unless-stopped