#version: '3'
services:
  node-red:
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - myNodeREDdata:/data
      #- /path/to/nodered/data:/data
    depends_on:
      - mqtt-broker
    restart: unless-stopped

  mqtt-broker:
    image: emqx/emqx:5.0.0
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "18083:18083"

volumes:
  myNodeREDdata: