services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer_app
    restart: always
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    networks:
      - portainer-network

networks:
  portainer-network:
    driver: bridge

volumes:
  portainer-data: