services:
  orb-docker:
    image: orbforge/orb:latest
    container_name: orb-sensor
    network_mode: bridge
    ports:
      - "7443:7443"
      - "5353:5353"
    volumes:
      - orb-data:/root/.config/orb  # Persists Orb configuration
    restart: always
    # Uncomment and adjust resources as needed
    # deploy:
    #   resources:
    #     limits:
    #       memory: 512m
    # labels:
    #   - 'com.centurylinklabs.watchtower.enable=true'  # Enable auto-updates with Watchtower
    #   - 'com.centurylinklabs.watchtower.scope=orb'    # Scope for Watchtower to monitor

  # Uncomment to enable automatic updates with Watchtower
  # watchtower:
  #   image: containrrr/watchtower
  #   container_name: watchtower
  #   restart: unless-stopped
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock  # Required to monitor other containers
  #   command: --label-enable --scope orb --interval 3600  # Check for updates every hour (3600s)

volumes:
  orb-data:  # Creates a named volume for persistent data
