#version: '3.9'

services:
  ghost-app:
    image: ghost:5.7.0-alpine
    container_name: ghost_app
    restart: always
    environment:
      database__client: mysql
      database__connection__host: ghost-db
      database__connection__user: ${MYSQL_USER}
      database__connection__password: ${MYSQL_PASSWORD}
      database__connection__database: ${MYSQL_DATABASE}
      url: http://192.168.1.8:8018
    ports:
      - 8018:2368
    volumes:
      - ghost-data:/var/lib/ghost/content
    depends_on:
      ghost-db:
        condition: service_healthy
    networks:
      - ghost-network

  ghost-db:
    image: mariadb:10.5.17
    container_name: ghost_db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ghost-network

networks:
  ghost-network:
    driver: bridge

volumes:
  ghost-data:
  db-data: