services:
  draw:
    image: excalidraw/excalidraw:latest
    restart: unless-stopped
    healthcheck:
      disable: true
    environment:
      - VIRTUAL_HOST=draw.ejemplo.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=draw.ejemplo.com
      - LETSENCRYPT_MAIL=pablo@ejemplo.com
      - REACT_APP_BACKEND_V1_GET_URL=https://draw.ejemplo.com/api/v1/
      - REACT_APP_BACKEND_V2_GET_URL=https://draw.ejemplo.com/api/v2/
      - REACT_APP_BACKEND_V2_POST_URL=https://draw.ejemplo.com/api/v2/post