services:
  db2rest-app:
    image: kdhrubo/db2rest:v1.6.4
    container_name: db2rest_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DRIVER=${DB_DRIVER}
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - db2rest-network

  postgres-db:
    image: postgres:15
    container_name: db2rest_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - db2rest-network

networks:
  db2rest-network:
    driver: bridge

volumes:
  postgres-data: